config/routes.rb
ECommerce::Application.routes.draw do

	get "logout" => "sessions#destroy", :as => "logout"
	get "login" => "sessions#new", :as => "login"
	get "register" => "users#new", :as => "register"
	
	resources :users
	resources :sessions
  resources :payment_notifications
  resources :carts
  resources :items
  match "current_cart" => "carts#show"
  match "delete_cart" => "carts#delete"
 
	get "aIndex" => "products#adminIndex", :as => "aIndex"
	get "index" => "products#index", :as => "index"
	
	get "cIndex" => "categories#index", :as => "cIndex"
	get "pIndex" => "products#index", :as => "pIndex"
	get "rIndex" => "reviews#index", :as => "rIndex"
	
	get "cEdit" => "categories#edit", :as => "cEdit"
	get "pEdit" => "products#edit", :as => "pEdit"
	get "rEdit" => "reviews#edit", :as => "rEdit"
	
	get "cNew" => "categories#new", :as => "cNew"
	get "pNew" => "products#new", :as => "pNew"
	get "rNew" => "reviews#new", :as => "rNew"
	
	get "cShow" => "categories#show", :as => "cShow"
	get "pShow" => "products#show", :as => "pShow"
	get "rShow" => "reviews#show", :as => "rShow"
	
	get "pSearch" => "products#search", :as => "pSearch", :via => :post

	root :to => "products#index"
	resources :categories
	resources :products
	resources :reviews

   match ':controller(/:action(/:id(.:format)))'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :item
  
  
  def inc?(item)
  self.item.each do |i|
     if i.product_id == item.id
       return true
     end
   end
   return false
 end
 #The following code is heavily based upon Ryan Bates at railscasts.com
 def paypal_encrypted(return_url, notify_url)
    values = {
      :business => 'test_s_1331012439_biz@aberdeen.ac.uk',
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => id,
      :currency_code=> 'GBP',
      :notify_url => notify_url,
      :cert_id => 'PA8NDBVB83X2A'
    }
    
    item.each_with_index do |item, index|
      values.merge!({
        "amount_#{index + 1}" => item.pPrice,
        "item_name_#{index + 1}" => item.pName,
        "item_number_#{index + 1}" => item.product_id,
        "quantity_#{index + 1}" => item.quantity
      })
    end
    encrypt_for_paypal(values)
  end
  #Set constants for certs.
PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

#Use OpenSSL to encrypt the values. Not nice but functional
def encrypt_for_paypal(values)
  signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
  OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
end

  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 def show
   @cart = current_cart
   @total = total_price @cart
 end
 def delete
   @cart = current_cart
   @cart.destroy
   session.delete(:cart_id)
   flash[:notice] = 'Cart succesfully deleted'
   redirect_to current_cart_path
 end
 private 
 def total_price cart
    total = 0.to_f
  end
 
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/purchase.html.erb
<% title "Thank you!" %>

<p><h>Thank you for your order!</h></p>
<p>It will be processed and dispatched shortly</p>
<p><%= link_to "Back to Products", products_path %></p>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<table>
<th>
	<th>Item</th>
	<th>Price</th>
	<th>Quantity</th>
	<th>Total</th>
</th>
<% @cart.item.each do |i|%>
<tr>
	<td>
		<a href="products/<%= i.product_id %>"><%= i.pName %></a>
	</td>
    <td>
        <%=number_to_currency i.pPrice %>
    </td>
    <td>
    	<%= f.text_field :quantity, :value => i.quantity %>
    </td>
    <td>
        <%= number_to_currency i.total %>
        <% @total += i.total %>
    </td>
  	<td>
  		<%= link_to 'Update Item', item_update_path(i.id) %>
  	</td>
</tr>
  <% end %>
 </table>
 <p> Total: <%= number_to_currency  @total %></p>
	

|
<%= link_to 'Continue Shopping', products_path %>
<%= link_to 'Delete Cart', delete_cart_path %>
<%= form_tag "https://www.sandbox.paypal.com/cgi-bin/webscr" do %>
  <%= hidden_field_tag :cmd, "_s-xclick" %>
  <%= hidden_field_tag :encrypted, @cart.paypal_encrypted(products_url, payment_notifications_url(:secret => "Nerf_Herder")) %>
  <p><%= submit_tag "Checkout" %></p>
<% end %>