config/routes.rb
ECommerce::Application.routes.draw do

	get "logout" => "sessions#destroy", :as => "logout"
	get "login" => "sessions#new", :as => "login"
	get "register" => "users#new", :as => "register"
	
	resources :users
	resources :sessions
  resources :payment_notifications
  resources :carts
  resources :items
  match "current_cart" => "carts#show"
  match "delete_cart" => "carts#delete"
 
	get "aIndex" => "products#adminIndex", :as => "aIndex"
	get "index" => "products#index", :as => "index"
	
	get "cIndex" => "categories#index", :as => "cIndex"
	get "pIndex" => "products#index", :as => "pIndex"
	get "rIndex" => "reviews#index", :as => "rIndex"
	
	get "cEdit" => "categories#edit", :as => "cEdit"
	get "pEdit" => "products#edit", :as => "pEdit"
	get "rEdit" => "reviews#edit", :as => "rEdit"
	
	get "cNew" => "categories#new", :as => "cNew"
	get "pNew" => "products#new", :as => "pNew"
	get "rNew" => "reviews#new", :as => "rNew"
	
	get "cShow" => "categories#show", :as => "cShow"
	get "pShow" => "products#show", :as => "pShow"
	get "rShow" => "reviews#show", :as => "rShow"
	
	get "pSearch" => "products#search", :as => "pSearch", :via => :post

	root :to => "products#index"
	resources :categories
	resources :products
	resources :reviews

   match ':controller(/:action(/:id(.:format)))'
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :review
	has_one :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def search
	@products = Product.find(:all, :order => params[:order]+" "+params[:type], :conditions => ["pName LIKE ?", "%#{params[:pName]}%"])
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
  @product = Product.find(params[:id])
	@reviews = Review.where(:rProduct => params[:id])
	session[:productId] = params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
	@categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
	@categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(:pName => params[:pName], :pDescription => params[:pDescription], :pPrice => params[:pPrice], :pPicture => params[:pPicture], :pSpec => params[:pSpec], :pCategory => params[:pCategory])
	if @product.save
		redirect_to :pIndex, :notice => "Product added to site"
	else
		render "new"
	end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

	if @product.update_attributes(:pName => params[:pName], :pDescription => params[:pDescription], :pPrice => params[:pPrice], :pPicture => params[:pPicture], :pSpec => params[:pSpec], :pCategory => params[:pCategory])
		redirect_to :pIndex, :notice => "Product updated"	
	else
		render edit
	end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pName %><br />
    <%= f.text_field :pName %>
  </div>
  <div class="field">
    <%= f.label :pDescription %><br />
    <%= f.text_area :pDescription %>
  </div>
  <div class="field">
    <%= f.label :pPrice %><br />
    <%= f.text_field :pPrice %>
  </div>
  <div class="field">
    <%= f.label :pPicture %><br />
    <%= f.text_field :pPicture %>
  </div>
  <div class="field">
    <%= f.label :pSpec %><br />
    <%= f.text_area :pSpec %>
  </div>
  <div class="field">
    <%= f.label :pCategory %><br />
    <%= f.number_field :pCategory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/adminIndex.html.erb
<h1>Administrator Area</h1>
<a href=cIndex>Category Index</a><br>
<a href=pIndex>Product Index</a><br>
<a href=rIndex>Review Index</a><br>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= form_for @product do |f| %>
	<p>
		Name:<br>
		<input id=pName type=text class=text name=pName autocomplete=off value=<%= @product.pName %>>
	</p>
	
	<p>
		Picture:<br>
		<input id=pPicture type=text class=text name=pPicture autocomplete=off value=<%= @product.pPicture %>>
	</p>
	
	<p>
		Price:<br>
		<input id=pPrice type=text class=text name=pPrice autocomplete=off value=<%= @product.pPrice %>>
	</p>
	
	<p>
		Description:<br>
		<textarea id="pDescription" name="pDescription" rows="10" cols="40"><%= @product.pDescription %></textarea>
	</p>
	
	<p>
		Specification:<br>
		<textarea id="pSpec" name="pSpec" rows="10" cols="40"><%= @product.pSpec %></textarea>
	</p>	
	
	<p>
		Category:<br>
		<select id=pCategory name=pCategory autocomplete=off>
			<option value=nil>-Select a Category-</option>
			<% @categories.each do |cat| %>
				<option value=<%= cat.id %><% if @product.pCategory == cat.id %> selected <% end %>>
					<%= cat.cName %>
				</option>
			<% end %>
		</select>
	</p>
	
	<p>
		<input id=submit type=submit class=button name=submit value="Update Product">
	</p>

	<p><a href="/pIndex">Back to Index</a></p>
<% end %>

app/views/products/index.html.erb
<h1>eCommerce Index</h1>

<p>
	<h2>Search for a Product</h2>
	<form action ="products/search" method="post">
		Product name: <input id=pName type=text class=text name=pName><br>
		Order by <select name=order>
			<option value=id>ID</option>
			<option value=pName>Name</option>
			<option value=pCategory>Category</option>
			<option value=pPrice>Price</option>
		</select>
		<select name=type>
			<option value="ASC">Ascending</option>
			<option value="DESC">Descending</option>
		</select><br>
		<input id=submit type=submit class=button name=submit value="Search">
	</form> 
</p>

<p>
	<h2>Product List</h2>
	<table>
	<% 
	counter = 0
	@products.each do |product|
	%>
		<% if (counter == 0) %>
			<tr> 
		<% end %>
			<td>
				<img src="<%= product.pPicture %>"><br>
				<a href="products/<%= product.id %>"><%= product.pName %></a><br>
				&#163;<%= product.pPrice %><br>
				<% if (product.pCategory <= 0) %> <%= "No Parent" %> <% else %> <%= Category.find(product.pCategory).cName %> <% end %><br>
				<%= link_to 'Edit', edit_product_path(product) %><br>
				<%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %><br>
			</td>
		<% if (counter == 2) %> 
			</tr> 
			<% counter = -1 %>
		<% end %>
		<% counter += 1 %>
	<% end %>
	</table>
</p>

<br />

<%= link_to 'New Product', new_product_path %><br>
<a href=aIndex>Return to Admin Index</a>

app/views/products/new.html.erb
<h1>New product</h1>

<%= form_for @product do |f| %>
	<p>
		Name:<br>
		<input id=pName type=text class=text name=pName autocomplete=off>
	</p>
	
	<p>
		Picture:<br>
		<input id=pPicture type=text class=text name=pPicture autocomplete=off>
	</p>
	
	<p>
		Price:<br>
		<input id=pPrice type=text class=text name=pPrice autocomplete=off>
	</p>
	
	<p>
		Description:<br>
		<textarea id="pDescription" name="pDescription" rows="10" cols="40"></textarea>
	</p>
	
	<p>
		Specification:<br>
		<textarea id="pSpec" name="pSpec" rows="10" cols="40"></textarea>
	</p>	
	
	<p>
		Category:<br>
		<select id=pCategory name=pCategory autocomplete=off>
			<option value=nil>-Select a Category-</option>
			<% @categories.each do |cat| %>
				<option value=<%= cat.id %>><%= cat.cName %></option>
			<% end %>
		</select>
	</p>
	
	<p>
		<input id=submit type=submit class=button name=submit value="Create Product">
	</p>

	<p><a href="/pIndex">Back to Index</a></p>
<% end %>

app/views/products/search.html.erb
<h1>Search results</h1>

<table>
<% 
counter = 0
@products.each do |product|
%>
	<% if ((counter % 5) == 0) %> <tr> <% end %>
		<td>
			<img src="<%= product.pPicture %>"><br>
			<a href="products/<%= product.id %>"><%= product.pName %></a><br>
			&#163;<%= product.pPrice %><br>
			<% if (product.pCategory <= 0) %> <%= "No Parent" %> <% else %> <%= Category.find(product.pCategory).cName %> <% end %><br>
		</td>
	<% if ((counter % 5) == 0) %> </tr> <% end %>
	<% counter += 1 %>
<% end %>
</table>

<p><a href="/pIndex">Back to Index</a></p>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<table cellspacing=25>
	<tr>
		<td>
			<img src="<%= @product.pPicture %>">
		</td>
		<td>
			<b><%= @product.pName %></b><br>
			&#163;<%= @product.pPrice %><br>
			<% if (@product.pCategory <= 0) %> <%= "No Parent" %> <% else %> <%= Category.find(@product.pCategory).cName %> <% end %><br>
			<%= link_to "Add to Cart", items_path(:product => @product), :method => :post %>
		</td>
	</tr>
	<tr>
		<td colspan=2>
			<hr>
			<h2>Description:</h2><br>
			<%= @product.pDescription %>
		</td>
	</tr>
	<tr>
		<td colspan=2>
			<hr>
			<h2>Specification:</h2><br>
			<%= @product.pSpec %>
		</td>
	</tr>
	<tr>
		<td colspan=2>
			<hr>
			<h2>Reviews:</h2><br>
			<% if can? :create, Review %>
			<a href="/reviews/new">Write Review</a><br>
			<% end %>
			<% @reviews.each do |review| %>
				<p><table>
					<tr><td><%= review.rTitle %> by <i><%= User.find_by_id(review.rPoster).email%></td></tr>
						<tr><td><%= review.rBody %></td></tr>
				</table></p>
			<% end %>
		</td>
	</tr>
</table>

<a href="../products">Back to Index</a>