config/routes.rb
ECommerce::Application.routes.draw do

	get "logout" => "sessions#destroy", :as => "logout"
	get "login" => "sessions#new", :as => "login"
	get "register" => "users#new", :as => "register"
	
	resources :users
	resources :sessions
  resources :payment_notifications
  resources :carts
  resources :items
  match "current_cart" => "carts#show"
  match "delete_cart" => "carts#delete"
 
	get "aIndex" => "products#adminIndex", :as => "aIndex"
	get "index" => "products#index", :as => "index"
	
	get "cIndex" => "categories#index", :as => "cIndex"
	get "pIndex" => "products#index", :as => "pIndex"
	get "rIndex" => "reviews#index", :as => "rIndex"
	
	get "cEdit" => "categories#edit", :as => "cEdit"
	get "pEdit" => "products#edit", :as => "pEdit"
	get "rEdit" => "reviews#edit", :as => "rEdit"
	
	get "cNew" => "categories#new", :as => "cNew"
	get "pNew" => "products#new", :as => "pNew"
	get "rNew" => "reviews#new", :as => "rNew"
	
	get "cShow" => "categories#show", :as => "cShow"
	get "pShow" => "products#show", :as => "pShow"
	get "rShow" => "reviews#show", :as => "rShow"
	
	get "pSearch" => "products#search", :as => "pSearch", :via => :post

	root :to => "products#index"
	resources :categories
	resources :products
	resources :reviews

   match ':controller(/:action(/:id(.:format)))'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	# GET /reviews
  # GET /reviews.json
	authorize_resource :except => [:show,:create]
	def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
	@product = Product.find(session[:productId])
	@products = Product.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
	@products = Product.all
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(:rTitle => params[:rTitle], :rBody => params[:rBody], :rPoster => current_user.id, :rProduct => params[:rProduct])

      if verify_recaptcha & @review.save
		redirect_to :controller => "products", :action => "show", :id => session[:productId], :notice => "Review added to product"
      else
		@product = Product.find(session[:productId])
        render "new"
      end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    if @review.update_attributes(:rTitle => params[:rTitle], :rBody => params[:rBody], :rProduct => params[:rProduct])
		redirect_to :rIndex, :notice => "Review updated"	
    else
		render edit
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rTitle %><br />
    <%= f.text_field :rTitle %>
  </div>
  <div class="field">
    <%= f.label :rBody %><br />
    <%= f.text_area :rBody %>
  </div>
  <div class="field">
    <%= f.label :rPoster %><br />
    <%= f.number_field :rPoster %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= form_for @review do |f| %>
	<p>
		Title:<br>
		<input id=rTitle type=text class=text name=rTitle autocomplete=off value=<%= @review.rTitle %>>
	</p>

	<p>
		Body:<br>
		<textarea id="rBody" name="rBody" rows="10" cols="40"><%= @review.rBody %></textarea>
	</p>
	
	<p>
		Product:<br>
		<select id=rProduct name=rProduct autocomplete=off>
			<option value=nil>-Select a Product-</option>
			<% @products.each do |product| %>
				<option value=<%= product.id %><% if @review.rProduct == product.id %> selected <% end %>><%= product.pName %></option>
			<% end %>
		</select>
	</p>
	
	<p>
		<input id=submit type=submit class=button name=submit value="Update Review">
	</p>
	
	<p><a href="/rIndex">Back to Index</a></p>
<% end %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Poster</th>
	<th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.rTitle %></td>
    <td><%= review.rBody %></td>
    <td><%= review.rPoster %></td>
    <td><%= Product.find(review.rProduct).pName %></td>
    <td><%= link_to 'Show', review %></td>
    <td>
		<% if can? :update, review %>
			<%= link_to 'Edit', edit_review_path(review) %>
		<% end %>
	</td>
    <td>
		<% if can? :destroy, review %>
		<%= link_to 'Destroy', review, confirm: 'Are you sure?', method: :delete %></td>
		<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %><br>
<a href=aIndex>Return to Admin Index</a>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= form_for @review do |f| %>
	<p>
		Title:<br>
		<input id=rTitle type=text class=text name=rTitle autocomplete=off>
	</p>

	<p>
		Body:<br>
		<textarea id="rBody" name="rBody" rows="10" cols="40"></textarea>
	</p>
	
	<p>
		<input id=rProduct type=hidden name=rProduct value=<%= @product.id %>>
	</p>
	<p>
		<%= recaptcha_tags =%>
	</p>
	
	<p>
		<input id=submit type=submit class=button name=submit value="Create Review">
	</p>
	
	<p><a href="/products/<%= @product.id %>">Back to Product</a></p>
<% end %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @review.rTitle %>
</p>

<p>
  <b>Body:</b>
  <%= @review.rBody %>
</p>

<p>
  <b>Poster:</b>
  <%= User.find(@review.rPoster).email %>
</p>

<p>
  <b>Product:</b>
  <%= @review.rProduct %>
</p>


<% if can? :update, @review %>
<%= link_to 'Edit', edit_review_path(@review) %>
 |<% end %>
<%= link_to 'Back', reviews_path %>